version: "3.8"

services:
  client:
    image: client
    build:
      context: ./client
    stdin_open: true
    ports:
      - "3000:3000"

  api:
    image: api
    build:
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGPASSWORD: postgres
      PGDATABASE: crypto_portfolio_tracker
      REDISPORT: 8001
      REDISHOST: redis
      PGPORT: 8000
      PORT: 3001

  postgres:
    image: postgres:14.1
    restart: always
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: crypto_portfolio_tracker
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    image: redis:7.0.2
    ports:
      - "8001:8001"
    command: ["redis-server", "--bind", "redis", "--port", "8001"]
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
